### ISSUE TITLE
Exam date for individual grade lists

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#31]
Currently `GradeInputList.ExamDate` is not set for an individual grade list. This sort of makes sense since there is no longer a single exam date, but there are a number of processes which assume this is not null for a submitted grade list. For example, I just got this error when submitting list 81693:
```
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Nullable`1.get_Value()
   at UvA.DataNose.Data.GradeInputEntry.<>c__DisplayClass28_0.<get_IsVURelevant>b__0(Enrolment z)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at UvA.DataNose.Data.GradeInputEntry.get_IsVURelevant()
   at UvA.DataNose.Data.UvAData.<>c.<AddVisibility>b__32_0(GradeInputEntry e)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at UvA.DataNose.Data.UvAData.AddVisibility(GradeInputList entity, Int32[] years)
   at UvA.DataNose.Data.UvAData.OnSavingChanges()
   at UvA.DataNose.Data.UvAData.SaveChanges()
   at UvA.DataNose.Core.DataContainer.SaveData(Boolean notify, UvAData data, String filePath, Int32 lineNumber, Boolean noTracking)
```

Maybe the exam date should be set anyway (say to the last date?), and/or we need to check all places where this is used?

**Comment by goomens** [comment]
It seems that indeed individual courses from the DataNose interface are now broken, e.g. in https://acc.datanose.nl/#course[77363]/gradeinput/list[69938] you are asked to enter an exam date per student (which you can't actually do since there is no UI for it 😄 ).

**Comment by rvankoten** [comment]
I think this was already fixed. However it's not clear if the other processes need to be changed in order to use examdate on grade entries.

**Comment by rvankoten** [comment]
Entry of examdate for student in UI is fixed.
Also for INOE courses the examdate is set to the earliest date of all entries in order not to break anything.
A new issue (#75) is created to check the uage of the examdate in other parts of DN.
